### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by dromer** [apiel/zicBox#3]
Please add a `LICENSE` to your project so we know under which terms it can be used :)

**Comment by apiel** [comment]
This funny because i was exactly looking at this right now. The problem is that i am a bit lost between all of the possibility... Seem like the GNU lincence is what would make sense to me but I am not.

I would like to make this code free of use, can be modified, and do what ever you want with it, as long it stay open source and all derived version stay open source (cause I want to promote open source code...). I am also fine if people use my code and design, to sell a product out of it, as long the origine of the project is mentioned.

Do you have any suggestion?

**Comment by dromer** [comment]
If you want the code and any changes (when distributed to users) to remain to be opensource then likely a GPL type license would indeed make sense. GPLv2 still had the "tivoization" issue for specific hardware signatures, so you might want to go for GPLv3 instead. Adding the `-or-later` clause means that it would also be future-compatible with any later versions of the license.

This page may help you out: https://choosealicense.com/

**Comment by apiel** [comment]
done in https://github.com/apiel/zicBox/commit/657585c34bbcb6405d35f3b3a2224f59a8fe7f94

Thx @dromer

**Comment by dromer** [comment]
Cool!

If you ever want to support the `-or-later` clause you'll have to explicitly mention it in the project description or the README.

cheers!

**Comment by dromer** [comment]
ps; for the code these days you can suffice by adding the appropriate SPDX identifier: https://spdx.org/licenses/ to the top comment.
