### ISSUE TITLE
Pi zero question

### ISSUE THREAD

**Issue by n9jcv** [apiel/zicBox#5]
Will this work with the original Pi zero or must it be a pi zero 2?

**Comment by apiel** [comment]
Raspberry Pi zero seem to be too slow, it least in test I was doing. I just received today rpi zero 2 and hope to get better result.
But with some work, I am sure there would be way to get it work...

And if it really too slow, maybe with using circle bare metal programming environment could help but then it would be so much work to get all the driver working and most likely SDL2 could not be use. Another option, might be to use an OLED display like SSD1306 and make UI much more basic...

I think everything is possible, but right now I focus on the most straight forward option because it is already so much work :-/

**Comment by n9jcv** [comment]
Sure Thank You very much!

**Comment by n9jcv** [comment]
Thanks
